### ISSUE TITLE
iOS not displaying notification when app in background/closed

### ISSUE THREAD

**Issue by Dec-** [wizpanda/cordova-plugin-firebase-lib#5]
## Describe the bug
Push notification working fine on Android but on iOS notification are not displaying when app is in background or closed. When app i opend and i push notification from Firebase console notification is visible but when i exit from app and do the same thing, notification is not visible.

## Steps to reproduce the behavior:

1. Go to Firebase Console
2. Trigger notification
3. iOS not displaying notification when app is closed or in background

## Plugin Version
cordova-plugin-firebase-lib 3.0.0 "Google Firebase Plugin"

## Smartphone (please complete the following information):

1. Device: iPad 3
2. OS: iOS10.3

## Additional context
When i open the application after sending notification from Firebase console and app was in the background, suddenly notification is visible...

Can some1 help?

**Comment by whoisaplex** [comment]
This is also happening for my team. Been stuck for over a week.

**Comment by sagrawal31** [comment]
Let us check that.

**Comment by sagrawal31** [comment]
Well, I just tried it on one of our production iOS releases and it is working.

![image](https://user-images.githubusercontent.com/1804514/58783878-aac98900-85ff-11e9-82b0-782a875c841e.png)


![image](https://user-images.githubusercontent.com/1804514/58783818-7e157180-85ff-11e9-9f5b-677cf9a68baf.png)

**Comment by whoisaplex** [comment]
Strange, once I put my app in the background, xcode says: Disconnected from FCM.

**Comment by sagrawal31** [comment]
I Googled "disconnected from FCM" and got https://github.com/arnesson/cordova-plugin-firebase/issues/888

**Comment by whoisaplex** [comment]
Yes, been looking at that thread but none of the solutions seems to fix the problem.

**Comment by swindex** [comment]
Make sure your xCode project Capabilities include "Background mode" -> "Remote Notifications"
Or add this to your config.xml
```xml
<platform name="ios">
     ......
        <config-file parent="UIBackgroundModes" platform="ios" target="*-Info.plist">
            <array>
                <string>remote-notification</string>
            </array>
        </config-file>
        <preference name="SplashScreen" value="screen" />
    </platform>
```

**Comment by jm555jm** [comment]
I fixed by add the following code:

AppDelegate+FirebasePlugin.m

swizzledDidFinishLaunchingWithOptions

add registerUserNotificationSettings
```
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(tokenRefreshNotification:)
                                                 name:kFIRInstanceIDTokenRefreshNotification object:nil];
    UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:UIUserNotificationTypeBadge |
                                            UIUserNotificationTypeAlert |
                                            UIUserNotificationTypeSound
                                                                             categories:nil];
    [[UIApplication sharedApplication] registerUserNotificationSettings:settings];
    self.applicationInBackground = @(YES);
```

and add this function
```
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings{
    [application registerForRemoteNotifications];
    
}
```

and setup Background mode -> Remote Notifications in info.plist

it will work

**Comment by sunhuafeng1992** [comment]
Does IOS background operation not receive notification have not been repaired yet? I did not solve my problem with the above scheme.

**Comment by sunhuafeng1992** [comment]
I often encounter the error of Invalid Apns Credential, but the certificate is not expired. I hope you can help me.

**Comment by eimermusic** [comment]
There is also this which can mess up iOS notifications. The problem is not identical to what I have experienced but close enough so that this might be contributing.

```
//    window.FirebasePlugin.hasPermission((data) => {
//      if (!data.isEnabled) {
        window.FirebasePlugin.grantPermission();
//      }
//    });
```
I.e. make sure you do not call hasPermission because you need to call grantPermission regardless of the return value.
